version: '3.8'
services:
  
  mysql:
    image: mysql:5.7
    ports:
      - "3307:3306"
    restart: always
    environment:
      MYSQL_DATABASE: 'DockerExam'
      
      MYSQL_PASSWORD: 'harshraj5565@'
      MYSQL_ROOT_PASSWORD: 'harshraj5565@'
    networks:
      - mynetwork
  backend:
    build: ./backend
    stdin_open: true
    ports:
      - "8000:8000"
    networks:
      - mynetwork
    depends_on:
      - mysql
  frontend:
    build: ./frontend
    stdin_open: true
    ports:
      - "3000:3000"
    depends_on:
      - backend
    networks:
      - mynetwork

networks:
  mynetwork:
    driver: bridge
volumes:
  mysql_data:
    driver: local
